name: Node CI

on: [push] # Корневой объект (root) должен начинаться с настроек

jobs:
  build-and-test: # Название задачи
    runs-on: ubuntu-latest

    steps: # И вот здесь, внутри steps, начинается список!
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci
